<#
.SYNOPSIS
    Установка TelePi на Windows — NSSM + конфиг + сервис
.DESCRIPTION
    1. Проверяет/устанавливает Node.js
    2. Скачивает NSSM (если нет)
    3. Создаёт ~\.config\telepi\config.env (если нет)
    4. Регистрирует Windows Service через NSSM
    5. Запускает сервис

.PARAMETER BotToken
    Telegram Bot Token (от @BotFather)

.PARAMETER UserIds
    Разрешённые Telegram User IDs (через запятую)

.PARAMETER Workspace
    Путь к рабочей директории (по умолчанию: C:\Users\%USERNAME%\projects)

.PARAMETER Instance
    Имя инстанса (если нужно зеркало)

.EXAMPLE
    # Интерактивная установка
    .\install-windows.ps1
    .\install-windows.ps1 -BotToken "123456:ABC" -UserIds "8570556962"
    .\install-windows.ps1 -BotToken "123456:ABC" -UserIds "8570556962" -Workspace "D:\projects"
#>

param(
    [string]$BotToken = '',
    [string]$UserIds = '',
    [string]$Workspace = '',
    [string]$Instance = ''
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ──────────────────────────────────────────────
# 1. Проверка Node.js
# ──────────────────────────────────────────────
Write-Host "`n🔍 Проверка Node.js..." -ForegroundColor Cyan
$node = Get-Command "node" -ErrorAction SilentlyContinue
if (-not $node) {
    Write-Host "❌ Node.js не найден." -ForegroundColor Red
    Write-Host "   Скачай: https://nodejs.org/ (v20+)"
    Write-Host "   Или через winget: winget install OpenJS.NodeJS.LTS"
    exit 1
}
$nodeVersion = node -v
Write-Host "   ✅ Node.js $nodeVersion" -ForegroundColor Green

# ──────────────────────────────────────────────
# 2. Проверка npm зависимостей
# ──────────────────────────────────────────────
Write-Host "`n📦 Проверка зависимостей..." -ForegroundColor Cyan
if (-not (Test-Path (Join-Path $ScriptDir "node_modules"))) {
    Write-Host "   ⏳ Устанавливаю npm packages..."
    Push-Location $ScriptDir
    try {
        npm install --production
        Write-Host "   ✅ Зависимости установлены" -ForegroundColor Green
    } finally {
        Pop-Location
    }
} else {
    Write-Host "   ✅ node_modules есть" -ForegroundColor Green
}

# ──────────────────────────────────────────────
# 3. NSSM
# ──────────────────────────────────────────────
Write-Host "`n🔧 Проверка NSSM..." -ForegroundColor Cyan

function Get-Nssm {
    $nssm = Get-Command "nssm.exe" -ErrorAction SilentlyContinue
    if ($nssm) { return $nssm.Source }

    $localNssm = Join-Path $ScriptDir "nssm.exe"
    if (Test-Path $localNssm) { return $localNssm }

    return $null
}

$nssmPath = Get-Nssm
if (-not $nssmPath) {
    Write-Host "   ⏳ Скачиваю NSSM..."
    $nssmUrl = "https://nssm.cc/release/nssm-2.24.zip"
    $zipPath = Join-Path $env:TEMP "nssm-2.24.zip"
    $extractPath = Join-Path $env:TEMP "nssm"

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $nssmUrl -OutFile $zipPath -UseBasicParsing
        Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force

        # Определяем архитектуру
        $arch = if ([Environment]::Is64BitOperatingSystem) { "win64" } else { "win32" }
        $nssmExe = Join-Path $extractPath "nssm-2.24" $arch "nssm.exe"

        Copy-Item $nssmExe (Join-Path $ScriptDir "nssm.exe") -Force
        $nssmPath = Join-Path $ScriptDir "nssm.exe"

        Remove-Item $zipPath -Force
        Remove-Item $extractPath -Recurse -Force

        Write-Host "   ✅ NSSM скачан: $nssmPath" -ForegroundColor Green
    } catch {
        Write-Error "   ❌ Не удалось скачать NSSM: $_"
        Write-Host "   Скачай вручную: https://nssm.cc/download"
        exit 1
    }
} else {
    Write-Host "   ✅ NSSM найден: $nssmPath" -ForegroundColor Green
}

# ──────────────────────────────────────────────
# 4. Конфиг
# ──────────────────────────────────────────────
Write-Host "`n⚙️  Настройка конфига..." -ForegroundColor Cyan

$configDir = Join-Path $HOME ".config" "telepi"
if ($Instance) {
    $configDir = Join-Path $configDir "instances" $Instance
}
$configPath = Join-Path $configDir "config.env"

if (-not (Test-Path $configPath)) {
    # Спрашиваем если не передали
    if (-not $BotToken) {
        $BotToken = Read-Host "   🤖 Telegram Bot Token (от @BotFather)"
    }
    if (-not $UserIds) {
        $UserIds = Read-Host "   👤 Твой Telegram User ID"
    }
    if (-not $Workspace) {
        $defaultWorkspace = Join-Path $HOME "projects"
        $Workspace = Read-Host "   📁 Путь к проектам (Enter = $defaultWorkspace)"
        if (-not $Workspace) { $Workspace = $defaultWorkspace }
    }

    New-Item -ItemType Directory -Path $configDir -Force | Out-Null

    $configContent = @"
# TelePi Configuration (Windows)
# Generated by install-windows.ps1

TELEGRAM_BOT_TOKEN=$BotToken
TELEGRAM_ALLOWED_USER_IDS=$UserIds
TELEPI_WORKSPACE=$Workspace

# Voice (optional, for transcription)
# OPENAI_API_KEY=sk-...
# SHERPA_ONNX_MODEL_DIR=C:\path\to\sherpa-onnx-model
# SHERPA_ONNX_NUM_THREADS=4

# PI_MODEL=anthropic/claude-sonnet-4-5
"@

    Set-Content -Path $configPath -Value $configContent -Encoding UTF8
    Write-Host "   ✅ Конфиг создан: $configPath" -ForegroundColor Green
} else {
    Write-Host "   ✅ Конфиг уже есть: $configPath" -ForegroundColor Green
    # Покажи текущий токен (маскированный)
    $content = Get-Content $configPath -Raw
    if ($content -match 'TELEGRAM_BOT_TOKEN=(\d+:\w+)') {
        $token = $matches[1]
        $masked = $token.Substring(0, [Math]::Min(6, $token.Length)) + '...' + $token.Substring([Math]::Max($token.Length - 4, 0))
        Write-Host "   Токен: $masked" -ForegroundColor Gray
    }
}

# ──────────────────────────────────────────────
# 5. Регистрация сервиса
# ──────────────────────────────────────────────
Write-Host "`n📦 Регистрация Windows Service..." -ForegroundColor Cyan

$serviceName = "TelePi"
if ($Instance) {
    $serviceName = "TelePi-$Instance"
}

# Проверка существующего сервиса
& $nssmPath status $serviceName 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Warning "⚠️  Сервис '$serviceName' уже существует."
    $overwrite = Read-Host "   Переустановить? (y/N)"
    if ($overwrite -ne 'y') {
        Write-Host "   Пропускаю. Для переустановки: .\telepi.ps1 remove ; .\telepi.ps1 install" -ForegroundColor Yellow
    } else {
        & $nssmPath stop $serviceName 2>$null | Out-Null
        Start-Sleep 1
        & $nssmPath remove $serviceName confirm 2>$null | Out-Null
        Start-Sleep 1
    }
}

# Установка сервиса
$nodePath = (Get-Command "node").Source
$fullCliPath = (Resolve-Path (Join-Path $ScriptDir "dist" "cli.js")).Path

& $nssmPath install $serviceName $nodePath "$fullCliPath start"
& $nssmPath set $serviceName AppDirectory $ScriptDir

if ($Instance) {
    & $nssmPath set $serviceName AppEnvironmentExtra "TELEPI_CONFIG=$configPath"
}

# Restart
& $nssmPath set $serviceName AppThrottle 0
& $nssmPath set $serviceName AppExit Restart
& $nssmPath set $serviceName AppRestartDelay 10000

# Logs
$logDir = Join-Path $HOME ".local" "state" "telepi" "logs"
New-Item -ItemType Directory -Path $logDir -Force | Out-Null
$instanceSuffix = if ($Instance) { "-$Instance" } else { "" }
& $nssmPath set $serviceName AppStdout (Join-Path $logDir "telepi$instanceSuffix.out.log")
& $nssmPath set $serviceName AppStderr (Join-Path $logDir "telepi$instanceSuffix.err.log")
& $nssmPath set $serviceName AppRotateFiles 1
& $nssmPath set $serviceName AppRotateOnline 1
& $nssmPath set $serviceName AppRotateBytes 10485760

Write-Host "   ✅ Сервис '$serviceName' зарегистрирован" -ForegroundColor Green

# ──────────────────────────────────────────────
# 6. Запуск
# ──────────────────────────────────────────────
Write-Host "`n🚀 Запуск сервиса..." -ForegroundColor Cyan
& $nssmPath start $serviceName

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n✅ TelePi запущен!" -ForegroundColor Green
    Write-Host "`n📋 Команды для управления:" -ForegroundColor Cyan
    Write-Host "   .\telepi.ps1 status$($Instance ? " --instance $Instance" : '')" -ForegroundColor White
    Write-Host "   .\telepi.ps1 stop$($Instance ? " --instance $Instance" : '')" -ForegroundColor White
    Write-Host "   .\telepi.ps1 start$($Instance ? " --instance $Instance" : '')" -ForegroundColor White
    Write-Host "   .\telepi.ps1 logs$($Instance ? " --instance $Instance" : '')" -ForegroundColor White
    Write-Host "`n📁 Логи: $logDir" -ForegroundColor Gray
} else {
    Write-Error "❌ Не удалось запустить сервис. Проверь конфиг и логи."
}
